debezium/debezium-server

debezium-server-bom/pom.xml
debezium-server-dist/pom.xml

https://issues.redhat.com/browse/DBZ-4038
Depends on https://github.com/debezium/debezium/pull/4231

DBZ-4038 Add all connectors to Server

---

debezium-server-pravega/pom.xml

https://issues.redhat.com/browse/DBZ-6057

DBZ-6057 Upgrade Netty version

---

debezium-server-redis/src/main/java/io/debezium/server/redis/RedisMemoryThreshold.java
debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java

https://issues.redhat.com/browse/DBZ-6346

DBZ-6346 Change severity of a log message for OOM

---

debezium-server-bom/pom.xml
debezium-server-dist/src/main/resources/assemblies/server-distribution.xml

https://issues.redhat.com/browse/DBZ-6147

DBZ-6147 Add/align dependencies required for Cassandra connector

---

debezium-server-core/src/test/resources/application.properties

https://issues.redhat.com/browse/DBZ-6574

DBZ-6574 Disabling k8 dev service by default to not interfere with SSL tests

---

debezium-server-bom/pom.xml
debezium-server-core/pom.xml
debezium-server-dist/pom.xml
debezium-server-eventhubs/pom.xml
debezium-server-http/pom.xml
debezium-server-infinispan/pom.xml
debezium-server-kafka/pom.xml
debezium-server-kinesis/pom.xml
debezium-server-nats-jetstream/pom.xml
debezium-server-nats-streaming/pom.xml
debezium-server-pravega/pom.xml
debezium-server-pubsub/pom.xml
debezium-server-pulsar/pom.xml
debezium-server-rabbitmq/pom.xml
debezium-server-redis/pom.xml
debezium-server-rocketmq/pom.xml

https://issues.redhat.com/browse/DBZ-6744
Depends on https://github.com/debezium/debezium/pull/4732

DBZ-6744 Decouple extension and server quarkus versions

---

debezium-server-redis/src/test/java/io/debezium/server/redis/RedisMemoryThresholdTest.java

Needed for https://github.com/debezium/debezium/pull/4877

DBZ-6952 Make test compatible

---

debezium-server-redis/src/main/java/io/debezium/server/redis/RedisMemoryThreshold.java
debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java
debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumerConfig.java
debezium-server-redis/src/test/java/io/debezium/server/redis/RedisMemoryThresholdTest.java

Squash of https://github.com/debezium/debezium-server/pull/61

DBZ-7117 Prevent OOM in Debezium Redis sink

---

debezium-server-kinesis/src/main/java/io/debezium/server/kinesis/KinesisChangeConsumer.java

https://issues.redhat.com/browse/DBZ-7417

DBZ-7417 Kinesis Sink Exception on PutRecord

---

debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java

https://issues.redhat.com/browse/DBZ-7435

feat: added an option to set a custom unique ordering key

---

debezium-server-pravega/pom.xml

https://issues.redhat.com/browse/DBZ-7449
Sibling PR to main repository upgrade of Quarkus to 3.2.9.Final -> https://github.com/debezium/debezium/pull/5234

DBZ-7449 Upgrade netty for Pravega to 4.1.100.Final

---

debezium-server-dist/src/main/resources/assemblies/server-distribution.xml

https://issues.redhat.com/browse/DBZ-7545

DBZ-7545 Add second dependencySet for implicit jakarta inclusion

---

debezium-server-rocketmq/src/test/java/io/debezium/server/rocketmq/RocketMqContainer.java

https://issues.redhat.com/browse/DBZ-7525
Requires also https://github.com/debezium/debezium/pull/5304 to be merged.

DBZ-7525 Use latest stable RocketMQ release for testing

---

debezium-server-redis/src/test/java/io/debezium/server/redis/TestUtils.java

https://issues.redhat.com/browse/DBZ-7564

DBZ-7564 Wait for Redis server to start

---

debezium-server-redis/src/test/java/io/debezium/server/redis/RedisTestResourceLifecycleManager.java
debezium-server-rocketmq/src/test/java/io/debezium/server/rocketmq/RocketMqContainer.java

https://issues.redhat.com/browse/DBZ-7557

DBZ-7557 Include Redis and RocketMQ logs into test log

---

debezium-server-redis/src/test/java/io/debezium/server/redis/RedisOffsetTestProfile.java

https://issues.redhat.com/browse/DBZ-7578

DBZ-7578 Use short flush interval in Redis offset tests

---

debezium-server-sqs/pom.xml

https://issues.redhat.com/browse/DBZ-7590

DBZ-7590 Add quick profile into SQS sink sub-module

---

pom.xml

https://issues.redhat.com/browse/DBZ-7369

DBZ-7369 Support all log levels

---

debezium-server-redis/src/test/java/io/debezium/server/redis/RedisSchemaHistoryIT.java

https://issues.redhat.com/browse/DBZ-7654

DBZ-7654 Fix RedisSchemaHistoryIT failure

---

debezium-server-redis/src/test/java/io/debezium/server/redis/RedisSchemaHistoryIT.java

https://issues.redhat.com/browse/DBZ-7692
https://issues.redhat.com/browse/DBZ-7701

Fix RedisSchemaHistoryIT tests

---

debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/BatchManager.java
debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventHubsChangeConsumer.java

https://issues.redhat.com/browse/DBZ-7585

DBZ-7585 Don't miss event when current batch is full

---

debezium-server-redis/pom.xml
debezium-server-redis/src/test/java/io/debezium/server/redis/RedisSchemaHistoryIT.java

https://issues.redhat.com/browse/DBZ-7723

DBZ-7723 Remove dependency on debezium-connector-mysql test-jar

---

debezium-server-bom/pom.xml
debezium-server-http/src/main/java/io/debezium/server/http/jwt/JWTAuthenticator.java

Needed for changes in core related to https://github.com/debezium/debezium/pull/5544

DBZ-7847 Fix apicurio deps alignment

---

debezium-server-bom/pom.xml
debezium-server-pravega/pom.xml
debezium-server-pravega/src/test/java/io/debezium/server/pravega/PravegaTestResource.java

https://issues.redhat.com/browse/DBZ-7841

DBZ-7841 Rollback to Quarkus 3.2.12

---

debezium-server-bom/pom.xml
debezium-server-dist/pom.xml
debezium-server-dist/src/main/resources/assemblies/server-distribution.xml
debezium-server-dist/src/main/resources/distro/conf/metrics.yml
debezium-server-dist/src/main/resources/distro/lib_metrics/enable_exporter.sh
debezium-server-dist/src/main/resources/distro/run.sh

https://issues.redhat.com/browse/DBZ-7913

DBZ-7913 Added Prometheus JMX exporter to server distribution

---

debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java

https://issues.redhat.com/browse/DBZ-7767

DBZ-7767 Allow empty config property values

---

pom.xml

https://issues.redhat.com/browse/DBZ-7224
Follows on https://github.com/debezium/debezium/pull/5654

DBZ-7224 Switched to centralised JDK version control

---

debezium-server-dist/src/main/resources/distro/conf/metrics.yml

Jira issue: https://issues.redhat.com/browse/DBZ-8037

DBZ-8037 Added `kafka.producer` metrics since this is not going to be used with a `kafka.connect` container

---

debezium-server-infinispan/pom.xml

http://issues.redhat.com/browse/DBZ-7840
Relates to https://github.com/debezium/debezium/pull/5533

DBZ-7840 Fix Infinispan 15 dependencies

---

debezium-server-bom/pom.xml
debezium-server-pravega/pom.xml
debezium-server-pravega/src/test/java/io/debezium/server/pravega/PravegaTestResource.java

https://issues.redhat.com/browse/DBZ-8095
Supplemental PR to the one in main https://github.com/debezium/debezium/pull/5711

DBZ-8095 Bump Netty to 4.1.108.Final and Pravega to 0.13.0

---

debezium-server-dist/pom.xml

https://issues.redhat.com/browse/DBZ-8186

DBZ-8186 Include MariaDB connector is distribution

---

debezium-server-bom/pom.xml

Depends on https://github.com/debezium/debezium/pull/5841

DBZ-8219 Override JAXB version deps

---

debezium-server-kafka/src/main/java/io/debezium/server/kafka/KafkaChangeConsumer.java

https://issues.redhat.com/browse/DBZ-8251

DBZ-8251 Sent records without waiting

---

debezium-server-core/pom.xml
debezium-server-dist/src/main/resources/distro/config/application.yaml.example

https://issues.redhat.com/browse/DBZ-8313

DBZ-8313 Added support for application.yaml in Debezium server by adding quarkus-config-yaml to POM

---

debezium-server-bom/pom.xml

https://issues.redhat.com/browse/DBZ-8357

Upgrade azure-messaging-eventhubs to 5.19.1

---

debezium-server-core/pom.xml

related to: https://github.com/debezium/debezium/pull/5960

DBZ-8351 Add possibility to store offsets into a config map with ConfigMapOffsetStore

---

debezium-server-core/pom.xml

closes: https://issues.redhat.com/browse/DBZ-8460

DBZ-8460 Add debezium-storage-jdbc to the distribution

---

debezium-system-tests/src/test/java/io/debezium/server/DebeziumServerPostgresIT.java

follow up for https://github.com/debezium/debezium/pull/6059

DBZ-8531 Improve DebeziumServerPostgresIT

---

debezium-server-pravega/pom.xml

https://issues.redhat.com/browse/DBZ-8601
Aligns with PR https://github.com/debezium/debezium/pull/6120

DBZ-8601 Align netty to 4.1.115.Final with Quarkus 3.15.3

---

debezium-system-tests/src/test/java/io/debezium/server/DebeziumServerPostgresIT.java

https://issues.redhat.com/browse/DBZ-8821

DBZ-8821 Fix DebeziumServerPostgresIT random test failure

---

debezium-server-instructlab/src/test/java/io/debezium/server/instructlab/InstructLabIT.java

https://issues.redhat.com/browse/DBZ-8883

DBZ-8883 InstructLabIT - Guard against file read/write race conditions

---

debezium-server-pulsar/src/main/java/io/debezium/server/pulsar/PulsarChangeConsumer.java

https://issues.redhat.com/browse/DBZ-8843

DBZ-8843 Shut down client immediatelly in cese of failure

---

debezium-server-milvus/src/main/java/io/debezium/server/milvus/MilvusChangeConsumer.java
debezium-server-milvus/src/test/java/io/debezium/server/milvus/MilvusIT.java
debezium-server-milvus/src/test/java/io/debezium/server/milvus/MilvusTestConfigSource.java
debezium-server-milvus/src/test/java/io/debezium/server/milvus/MilvusTestResourceLifecycleManager.java
debezium-server-milvus/src/test/java/io/debezium/server/milvus/VectorPostgresTestResourceLifecycleManager.java

https://issues.redhat.com/browse/DBZ-8909

DBZ-8909 Allow handling of JSON as native JSON type

---

debezium-system-tests/src/test/java/io/debezium/server/DebeziumServerPostgresIT.java

https://issues.redhat.com/browse/DBZ-8928

DBZ-8928 Prevent race condition during assertion

---

debezium-server-core/src/main/java/io/debezium/server/ConnectorLifecycle.java
debezium-server-core/src/main/java/io/debezium/server/events/PollingStartedEvent.java
debezium-server-core/src/main/java/io/debezium/server/events/PollingStoppedEvent.java

https://issues.redhat.com/browse/DBZ-8948

DBZ-8948 Add polling start and stop events

---

debezium-server-dist/pom.xml

https://issues.redhat.com/browse/DBZ-9015
Depends on https://github.com/debezium/debezium/pull/6394

DBZ-9015 Add IBMi connector to distribution

---

debezium-server-pravega/pom.xml

https://issues.redhat.com/browse/DBZ-9032

DBZ-9032 Revert update to Netty 4.1.119.Final

---

debezium-server-core/src/test/java/io/debezium/server/DebeziumServerConnectFormatIT.java
debezium-server-redis/src/test/java/io/debezium/server/redis/RedisStreamMessageIT.java

related to: https://github.com/debezium/debezium/pull/6430

DBZ-9020 Align test check for headers

---

debezium-server-core/pom.xml

requires: https://github.com/debezium/debezium/pull/6496

DBZ-9110 Align core changes

---

debezium-server-core/pom.xml
debezium-server-eventhubs/pom.xml
debezium-server-http/pom.xml
debezium-server-infinispan/pom.xml
debezium-server-instructlab/pom.xml
debezium-server-kafka/pom.xml
debezium-server-kinesis/pom.xml
debezium-server-milvus/pom.xml
debezium-server-nats-jetstream/pom.xml
debezium-server-nats-streaming/pom.xml
debezium-server-pravega/pom.xml
debezium-server-pubsub/pom.xml
debezium-server-pulsar/pom.xml
debezium-server-qdrant/pom.xml
debezium-server-rabbitmq/pom.xml
debezium-server-redis/pom.xml
debezium-server-rocketmq/pom.xml
debezium-server-sqs/pom.xml
debezium-system-tests/pom.xml

https://issues.redhat.com/browse/DBZ-9246

DBZ-9246 Switch to smallrye jandex pluing

---

debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/BatchManager.java
debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventDataBatchProxy.java

https://issues.redhat.com/browse/DBZ-9304

DBZ-9304 Clear dynamic batches between batch calls

---

debezium-server-core/src/test/java/io/debezium/server/DebeziumServerIT.java

Depends on https://github.com/debezium/debezium/pull/6634

DBZ-9300 Build with Kafka 4.x

---

debezium-server-core/src/main/java/io/debezium/server/BaseChangeConsumer.java
debezium-server-kafka/src/main/java/io/debezium/server/kafka/KafkaChangeConsumer.java

https://issues.redhat.com/browse/DBZ-9378

DBZ-9378 Support different types in log message

---

debezium-server-nats-jetstream/src/main/java/io/debezium/server/nats/jetstream/NatsJetStreamChangeConsumer.java

Adds support for publishAsync to nats jetstream sink
- Implements an async method to nats jetstream sink.

DBZ-9474 Adds support for publishAsync to nats jetstream sink

---

debezium-server-core/pom.xml
debezium-server-core/src/main/java/io/debezium/server/ChangeConsumerFactory.java
debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
debezium-server-core/src/main/java/io/debezium/server/DefaultChangeConsumer.java
debezium-server-core/src/test/java/io/debezium/server/DebeziumServerTest.java
debezium-server-dist/src/test/resources/redis/docker-compose.yml
debezium-server-kafka/pom.xml
debezium-server-kafka/src/test/java/io/debezium/server/kafka/KafkaBaseIT.java
debezium-server-kafka/src/test/java/io/debezium/server/kafka/KafkaIT.java
debezium-server-kafka/src/test/java/io/debezium/server/kafka/KafkaOpenLineageIT.java
debezium-server-kafka/src/test/java/io/debezium/server/kafka/OpenLineageProfile.java
debezium-server-kafka/src/test/resources/openlineage/openlineage.yml

closes: https://issues.redhat.com/browse/DBZ-9059

DBZ-9059 Enable OpenLineage output dataset events on Debezium Server
