debezium/debezium-server

- README.md
- debezium-server-http/src/main/java/io/debezium/server/http/Authenticator.java
- debezium-server-http/src/main/java/io/debezium/server/http/HttpChangeConsumer.java
- debezium-server-http/src/main/java/io/debezium/server/http/jwt/JWTAuthenticator.java
- debezium-server-http/src/main/java/io/debezium/server/http/jwt/JWTAuthenticatorBuilder.java
- debezium-server-http/src/main/java/io/debezium/server/http/jwt/JWTAuthorizationInitialRequest.java
- debezium-server-http/src/main/java/io/debezium/server/http/jwt/JWTAuthorizationRefreshRequest.java
- debezium-server-http/src/main/java/io/debezium/server/http/jwt/JWTAuthorizationResponse.java
- debezium-server-http/src/test/java/io/debezium/server/http/HttpChangeConsumerTest.java
- debezium-server-http/src/test/java/io/debezium/server/http/jwt/JWTAuthenticatorBuilderTest.java
- debezium-server-http/src/test/java/io/debezium/server/http/jwt/JWTAuthenticatorTest.java
This PR adds a JWT authentication option to the HTTP Client sink (see [DBZ-6348](https://issues.redhat.com/browse/DBZ-6348)).  If the JWT authentication is specified, the client will have the authenticator check for an active authentication token.  If there is no token or its expired, the authenticator will make a request for an initial or refresh token.  The authentication details will then be added to the HTTP request header.
The following options are added to the config file:
* `debezium.sink.http.authentication.type`: If missing, no authentication is used.  If present, its value specifies the authentication protocol.  The only currently supported value is `jwt`.
* `debezium.sink.http.authentication.jwt.username`: Specify the username
* `debezium.sink.http.authentication.jwt.password`: …
> DBZ-6348 Add JWT authentication to HTTP Client

- debezium-server-http/src/main/java/io/debezium/server/http/Authenticator.java
- debezium-server-http/src/main/java/io/debezium/server/http/HttpChangeConsumer.java
- debezium-server-http/src/main/java/io/debezium/server/http/jwt/JWTAuthenticator.java
- debezium-server-http/src/test/java/io/debezium/server/http/jwt/JWTAuthenticatorTest.java
Set (overwrite if exists) authorization headers rather than adding them (resulting in duplicates).  Fixes [DBZ-6405](https://issues.redhat.com/browse/DBZ-6405).
> DBZ-6405 Set (instead of adding) Authorization Headers

- debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java
- debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubLiteChangeConsumer.java
Add properties 
`debezium.sink.pubsub.wait.message.computation.timeout.ms` and `debezium.sink.pubsublite.wait.message.computation.timeout.ms`
to configure the wait time on message processing by Google PubSub. In this wait the connector can fail and be restarted.
Doc PR https://github.com/debezium/debezium/pull/4544
> DBZ-6461 Debezium Server cannot recover from Google Pub/Sub errors

- debezium-server-rabbitmq/src/main/java/io/debezium/server/rabbitmq/RabbitMqStreamChangeConsumer.java
- debezium-server-rabbitmq/src/test/java/io/debezium/server/rabbitmq/RabbitMqIT.java
Changelogs:
- exchange (optional)
- autoCreateRoutingKey (optional, default true)
- routingKeyDurable (optional, default true)
- deliveryMode (optional, default 2)
- set routingKey to be using topic name, as @jpechane ask @olivierboudet from previous [PR review comments](https://github.com/debezium/debezium-server/pull/13#pullrequestreview-1360181651)
[Docs PR](https://github.com/debezium/debezium/pull/4684)
> Add more config for rabbitmq connector

- debezium-server-dist/pom.xml
https://issues.redhat.com/browse/DBZ-6701
> DBZ-6701 enabling JNDI in order to support SRV protocol in MongoDB connector

- debezium-server-kinesis/src/main/java/io/debezium/server/kinesis/KinesisChangeConsumer.java
https://issues.redhat.com/browse/DBZ-7032
> DBZ-7032 Implement Retries for Amazon Kinesis Event Transmittion

- debezium-server-http/pom.xml
- debezium-server-http/src/test/java/io/debezium/server/http/HttpIT.java
- debezium-server-http/src/test/java/io/debezium/server/http/HttpTestResourceLifecycleManager.java
- debezium-server-infinispan/src/test/java/io/debezium/server/infinispan/InfinispanSinkConsumerIT.java
https://issues.redhat.com/browse/DBZ-7077
https://issues.redhat.com/browse/DBZ-7092
> DBZ-7077 Use jakarta.inject.Inject instead of com.google.inject.Inject

- README.md
- debezium-server-eventhubs/pom.xml
- debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/BatchManager.java
- debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventDataBatchProxy.java
- debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventHubsChangeConsumer.java
- debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsTestConfigSource.java
- debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsWithPartitionKeyIT.java
- debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsWithPartitionKeyProfile.java
- debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsWithPartitionRouterIT.java
- debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsWithPartitionRouterProfile.java
- debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsWithStaticPartitionIdIT.java
- debezium-server-eventhubs/src/test/java/io/debezium/server/eventhubs/EventHubsWithStaticPartitionIdProfile.java
Link: https://issues.redhat.com/browse/DBZ-6723
With the existing Azure EventHubs sink implementation it is not possible to leverage multiple partitions on the EventHubs side. One can either hardcode the partitionID where _all_ messages will be sent to, or a fixed partitionKey, which will make EventHubs pick a single partition derived from that key. Being only able to leverage a single partition makes it hard to parallelise any downstream processing. This is something we ran into when processing ~900GB of messages from a single large database server.
The EventHubs SDK only allows specifying the partition (either via an ID or a key) on a batch level, as the entire batch of messages is being emitted as a single message under the hood. This means that in order to send messages to N …
> DBZ-6723 Allow specifying partitions for EventHub

- debezium-server-http/src/test/java/io/debezium/server/http/HttpIT.java
@jpechane, @Naros, looks like a missing leftover from DBZ-7216 to me. That being said, I'm somewhat doubtful about this change in the first place:
* It seems unexpected in a non-minor release?
* If it actually should be changed, the [documentation](https://debezium.io/documentation/reference/stable/integrations/cloudevents.html) needs updating as well
* Is there a CI build missing which would have flagged this early on?
> DBZ-7216 Adjusting to changed CE type value

- debezium-server-pubsub/src/test/java/io/debezium/server/pubsub/PubSubIT.java
- debezium-server-rabbitmq/src/main/java/io/debezium/server/rabbitmq/RabbitMqStreamChangeConsumer.java
- debezium-server-rabbitmq/src/main/java/io/debezium/server/rabbitmq/RabbitMqStreamNativeChangeConsumer.java
Depends on https://github.com/debezium/debezium/pull/5139
> DBZ-7098 Test deletes for PubSub

- debezium-server-http/src/main/java/io/debezium/server/http/HttpChangeConsumer.java
https://issues.redhat.com/browse/DBZ-6955
> DBZ-6955 Treat HTTP/2 GOAWAY responses as retriable

- debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
- debezium-server-http/src/test/java/io/debezium/server/http/HttpTestConfigSource.java
Add option to specify embedded engine factory builder and switch HTTP tests to async embedded engine.
https://issues.redhat.com/browse/DBZ-7470
> DBZ-7470 Add option to specify embedded engine factory builder

- debezium-server-redis/src/test/java/io/debezium/server/redis/RedisTestResourceLifecycleManager.java
When the Redis container uses random port, even single test fails with `Unexpected end of stream` exception on my machine. I observed that it starts working when Redis uses fixed port. Unfortunatelly I have no clue what is the root cause.
Try to switch to fixed port and see if it helps also on the CI and the testsuite will be more stable. Or vice versa - if it makes things worse and there will be port conflicts.
https://issues.redhat.com/browse/DBZ-7576
> DBZ-7576 Use fixed port for Redis server

- debezium-server-bom/pom.xml
- debezium-server-pravega/pom.xml
- debezium-server-pravega/src/test/java/io/debezium/server/pravega/PravegaTestResource.java
https://issues.redhat.com/browse/DBZ-7841
* Bumped pravega-client to 0.13.0
* Aligned netty to 4.1.107.Final
> DBZ-7841 Align dependencies with Quarkus 3.8.3

- debezium-server-dist/src/main/resources/distro/conf/metrics.yml
Otherwise metrics show up as `untyped`
Also added `kafka.producer` metrics since this is not going to be used with a `kafka.connect` container
> DBZ-8036 Added `type` to Prometheus JMX exporter

- debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
Sister PR: https://github.com/debezium/debezium/pull/5674
This PR in combination with a PR from Debezium Server supports the ability to do custom converters. Internally we have multiple custom converters and needed to build our own modules and hardcore our class names.
Now we can do the following: (operator spec)
```
type: clientprovided
config:
class: com.shopify.cdc.transforms.ByteArrayHeaderConverter
```
Related Issue: https://issues.redhat.com/browse/DBZ-8040
> DBZ-8040: Custom Converter Support

- debezium-server-rabbitmq/src/main/java/io/debezium/server/rabbitmq/RabbitMqStreamNativeChangeConsumer.java
When use rabbitmq native stream as sink for dbz, it will produce error as like: "Error while creating stream connection to fdb49ba7df14:5552. fdb49ba7df14: Name or service not known. This may be due to the usage of a load balancer that makes topology discovery fail. Use a custom AddressResolver or the --load-balancer flag if using StreamPerfTest".
From the docs https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#understanding-connection-logic
We need to use options "AddressResolver" to let it connect successful
> DBZ-8108 implemente option AddressResolver for rabbitmq native stream

- debezium-server-kafka/src/main/java/io/debezium/server/kafka/KafkaChangeConsumer.java
Resolve futures before marking a batch as completed for Kafka sink
This will make sure that records are being send or we crash the sink instead of sink being blocked forever.
> DBZ-7575 Resolve all futures before marking a batch as completed in Kafka sink

- debezium-server-kafka/src/main/java/io/debezium/server/kafka/KafkaChangeConsumer.java
Enriched the `KafkaChangeConsumer` ERROR log with record key.
> DBZ-8282 Added record key to KafkaChangeConsumer ERROR log.

- debezium-server-core/pom.xml
- debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
- debezium-server-core/src/main/java/io/debezium/server/DebeziumServerConfig.java
- debezium-server-core/src/main/java/io/debezium/server/rest/DebeziumServerAPI.java
- debezium-server-core/src/main/java/io/debezium/server/rest/signal/DSSignal.java
- debezium-server-core/src/main/java/io/debezium/server/rest/signal/SignalResource.java
- debezium-server-core/src/main/resources/application.properties
- debezium-server-core/src/test/java/io/debezium/server/DebeziumServerIT.java
- debezium-server-core/src/test/java/io/debezium/server/TestConfigSource.java
- debezium-server-core/src/test/resources/application.properties
https://issues.redhat.com/browse/DBZ-8101
> DBZ-8101 Initial implementation of signal REST API for DS

- debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
When launching debezium-server via:
``` bash
java -jar ./debezium-server-dist/target/debezium-server-dist-3.0.0-SNAPSHOT-runner.jar io.debezium.server.Main
```
it errors out with the log-line:
```
Failed to load mandatory config value 'debezium.sink.type'. Please check you have a correct Debezium server config in /<redacted>/debezium/debezium-server/conf/application.properties or required properties are defined via system or environment variables.
```
This is broken in two ways:
- the printed path is wrong. quarkus loads application.properties from the `config` directory: https://quarkus.io/guides/config-reference
- the error message is logged via println. LOGGER should be used instead (otherwise depending on the logging-setup the message might be dropped - due to not being json)
This PR …
> DBZ-8367: fix error message: show the correct config-path & format

- debezium-server-rabbitmq/src/main/java/io/debezium/server/rabbitmq/RabbitMqStreamChangeConsumer.java
- debezium-server-rabbitmq/src/main/java/io/debezium/server/rabbitmq/RabbitMqStreamNativeChangeConsumer.java
Done based on the principle of: https://github.com/debezium/debezium-server/pull/96
Link issue:
https://issues.redhat.com/browse/DBZ-8307
> DBZ-8307 Fix loss data issue for RabbitMQ

- debezium-server-bom/pom.xml
Bumping the Kinesis version to 2.17.241 will resolve the jackson incompatibility issue when running the Debezium server:
```
2024-12-11 11:25:23,166 ERROR [io.deb.ser.ConnectorLifecycle] (pool-7-thread-1) Connector completed: success = 'false', message = 'java.lang.NoSuchFieldError: Class com.fasterxml.jackson.databind.PropertyNamingStrategy does not have member field 'com.fasterxml.jackson.databind.PropertyNamingStrategy PASCAL_CASE_TO_CAMEL_CASE'', error = 'java.lang.NoSuchFieldError: Class com.fasterxml.jackson.databind.PropertyNamingStrategy does not have member field 'com.fasterxml.jackson.databind.PropertyNamingStrategy PASCAL_CASE_TO_CAMEL_CASE'': java.lang.NoSuchFieldError: Class com.fasterxml.jackson.databind.PropertyNamingStrategy does not have member field …
```
> DBZ-8517: Bump Kinesis version to 2.17.241 to fix Jackson incompatibility when using the sink Kinesis

- .github/workflows/cross-maven.yml
- debezium-server-dist/src/test/resources/redis/application.properties
- debezium-server-dist/src/test/resources/redis/docker-compose.yml
Added a new job to validate the distribution works for each of the supported sinks. For now, I only added the "redis" sink. 
Fixes https://issues.redhat.com/browse/DBZ-3226
> DBZ-3226: Add step to verify the Debezium-server distribution

- debezium-server-rocketmq/src/test/java/io/debezium/server/rocketmq/RocketMqContainer.java
Docker Hub is no longer contacted for image version calculation so the code uses a static one
> DBZ-8564 Use static container version

- debezium-server-pulsar/src/main/java/io/debezium/server/pulsar/PulsarChangeConsumer.java
The issue described in [Jira ticket](https://issues.redhat.com/browse/DBZ-8563) has evolved into a feature request that this PR addresses.
In summary, to enable batching and improve the throughput of Pulsar's KeyShared subscription, the producer must be configured with `BatcherBuilder.KEY_BASED`, as pointed out in the official Pulsar documentation:
- https://pulsar.apache.org/docs/next/concepts-messaging/#batching-for-key_shared-subscriptions
This PR introduces the ability to configure the BatcherBuilder for the Debezium Pulsar producer. For example, you can now configure it as follows:
```
debezium.sink.type=pulsar
debezium.sink.pulsar.client.serviceUrl=pulsar://localhost:6650
debezium.sink.pulsar.producer.producerName=debezium_test_pulsar_batching …
```
> DBZ-8563 Add support for setting BatcherBuilder in Pulsar Producer

- debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java
Hi there,
Made adjustments to include concurrency and compression to pub/sub:
https://cloud.google.com/pubsub/docs/concurrency-control-messages
https://cloud.google.com/pubsub/docs/compress-messages
Set the default concurrency threads to 1 as I imagine anyone setting concurrency to true has some specific goal in mind and will almost certainly adjust.  The compression threshold I set is the default value as per the docs.
> DBZ-8715 Added message compression and concurrency control

- debezium-server-nats-jetstream/src/main/java/io/debezium/server/nats/jetstream/NatsJetStreamChangeConsumer.java
- debezium-server-nats-streaming/src/main/java/io/debezium/server/nats/streaming/NatsStreamingChangeConsumer.java
Howdy, 
Nats consumers would crash when using binary serialization like avro because of a bad logging statement that tried to force the record value to a string or throws. This removes that unnecessary string conversion.
The relevant error log looks like 
```
{"timestamp":"2025-02-11T18:30:51.99Z","sequence":227,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"io.debezium.server.ConnectorLifecycle","level":"ERROR","message":"Connector completed: success = 'false', message = 'io.debezium.DebeziumException: Unexpected data type '[B'', error = 'io.debezium.DebeziumException: Unexpected data type '[B''","threadName":"pool-7-thread-1","threadId":26,"mdc":{},"ndc":"","hostName":"debezium","processName":"io.debezium.server.Main","processId":1,"exception":{"refId":1,"exceptionType":"io …
```
> fix binary serialization with nats consumer

- debezium-server-pubsub/src/main/java/io/debezium/server/pubsub/PubSubChangeConsumer.java
Related Issue: https://issues.redhat.com/browse/DBZ-8735
This PR adds support for connecting to Google Cloud Pub/Sub locational endpoints by introducing a new configuration parameter `debezium.sink.pubsub.region`. 
The implementation leverages the standard `Publisher.Builder`'s `setEndpoint` method to establish connections to locational endpoints. 
ref: https://cloud.google.com/java/docs/reference/google-cloud-pubsub/latest/com.google.cloud.pubsub.v1.Publisher.Builder
The parameter is named 'region' instead of 'locational.endpoint' to maintain consistency with other sinks like Kinesis and PubSub Lite.
> DBZ-8735: Add support for Google Cloud Pub/Sub locational endpoints

- debezium-server-core/src/main/java/io/debezium/server/DebeziumServer.java
- debezium-server-core/src/test/java/io/debezium/server/DebeziumServerConnectFormatIT.java
- debezium-server-core/src/test/java/io/debezium/server/DebeziumServerConnectFormatProfile.java
https://issues.redhat.com/browse/DBZ-8782
> DBZ-8782 Allow key and value format of type Connect

- debezium-server-dist/src/main/resources/assemblies/server-distribution-prod.xml
- debezium-server-dist/src/main/resources/assemblies/server-distribution.xml
See https://issues.redhat.com/projects/DBZ/issues/DBZ-8863
Relates to this conversation:  https://debezium.zulipchat.com/#narrow/channel/350571-community-dbz-server/topic/java.2Elang.2ENoClassDefFoundError.3A.20org.2Fyaml.2Fsnakeyaml
> DBZ-8863 Explicitly include SnakeYAML, required by quarkus-config-yaml

- debezium-server-kinesis/src/main/java/io/debezium/server/kinesis/KinesisChangeConsumer.java
- debezium-server-kinesis/src/test/java/io/debezium/server/kinesis/KinesisUnitTest.java
https://issues.redhat.com/browse/DBZ-8893
Use batchRequest.get(index) instead of putRecordsRequestEntryList.get(index) when creating the list of failed records for retry. Add test for successive retries
> DBZ-8893 Fix KinesisChangeConsumer so that it retries failed records.

- debezium-server-pravega/pom.xml
https://issues.redhat.com/browse/DBZ-8906
> DBZ-8906 Update Netty to 4.1.118.Final with Quarkus 3.15.4 LTS

- debezium-server-nats-jetstream/src/test/java/io/debezium/server/nats/jetstream/NatsJetStreamTestConfigSource.java
If the subjects are not specified, `*.*.*` is used.
https://issues.redhat.com/browse/DBZ-8985
> DBZ-8985 Don't use wildcards in stream subjects

- debezium-server-pravega/pom.xml
https://issues.redhat.com/browse/DBZ-9032
Sibling PR of https://github.com/debezium/debezium/pull/6408
> DBZ-9032 Align Netty to 4.1.119.Final used by Quarkus 3.20.1

- debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java
_Open for review but should not be merged before the change in https://github.com/debezium/debezium/pull/6459 makes it in debezium-core._
The configuration options are used when creating connections to Redis and are mainly used in the debezium-storage-redis module in debezium.
There is one additional use in the RedisStreamChangeConsumer in debezium-server-redis which is updated as part of this commit.
This update uses a factory method that creates a RedisConnection directly from a shared configuration object (RedisCommonConfig). Previously, both Debezium and Debezium Server needed to duplicate any changes made to Redis connection parameters, leading to tight coupling and maintenance overhead. By centralizing connection creation through a common config, any updates to the Redis connection …
> DBZ-9082 Add options to specify custom keystore and truststore for Redis sink

- debezium-server-redis/src/test/java/io/debezium/server/redis/RedisSSLOptionsStreamIT.java
- debezium-server-redis/src/test/java/io/debezium/server/redis/RedisSSLOptionsStreamTestProfile.java
This change tests streaming data to a Redis sink configured with custom SSL options (keystore/truststore etc.)
The test is similar to an existing test (RedisSSLStreamIT) but specifies the SSL settings through debezium configuration properties specific to the Redis sink instead of system properties.
For more context see [DBZ-9082](https://issues.redhat.com/browse/DBZ-9082) and https://github.com/debezium/debezium/pull/6459
> DBZ-9082 Add integration test for streaming to Redis sink with customSSL options

- debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/BatchManager.java
- debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventHubsChangeConsumer.java
When no explicit partitionId or partitionKey was configured, the system was using `record.partition()` which could be null, and then falling back to `BATCH_INDEX_FOR_NO_PARTITION_ID` (-1)
This caused all messages to have null partition IDs.
This PR modifies the partition selection logic to use `record.key()` as the partition key when no explicit partitioning is configured. This matches the behavior of other sinks like Kinesis, which already use `record.key()`
> Implement dynamic partition key support for Azure Event Hub sink

- debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/EventHubsChangeConsumer.java
- debezium-server-eventhubs/src/main/java/io/debezium/server/eventhubs/HashFunction.java
Az event hub partition keys are limited to a max of 128 chars.
When debezium tries to send a partition key longer than 128 chars, it throws an exception and terminates the connector. 
This PR implements a new feature to optionally hash message keys to better support usage of the sink.
New optional sink config:
- debezium.sink.eventhubs.hashmessagekeyfunction # empty by default (no hashing of message key) – supported values: java, md5, sha1, sha256
> DBZ-9245: Azure Event Hub Feature - Hash Message Key

- debezium-server-dist/src/main/resources/distro/jmx/enable_jmx.sh
DBZ-9352 tiny fix to ensure JAVA_OPTS is correct when jmxremote.access/jmxremote.password are absent
> DBZ-9352 tiny fix to ensure JAVA_OPTS is correct when jmxremote.access/jmxremote.password are absent

- debezium-server-core/src/main/java/io/debezium/server/DebeziumMetrics.java
Partial solution for https://issues.redhat.com/browse/DBZ-9477.
The problem is SQL Server connector metrics are split between several mbeans ([task- and partition-scoped](https://github.com/debezium/debezium/blob/v3.3.0.Beta1/debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics/SqlServerStreamingTaskMetrics.java)).
This PR is not a general solution for the problem but it allows to use DebeziumMetrics when SQL Server connector is configured with 1 task and 1 database (partition) and should not affect other connectors.
> DBZ-9477: support partition-scoped SQL Server connector metrics
